name: MitchGenerators
version: '1.0'
main: me.reklessmitch.mitchgenerators.MitchGenerators
api-version: '1.19'
author: ReklessMitch
description: A plugin that allows you to create custom generators
depend: [ MassiveCore ]
